networks:
  net:
    name: fabric_network

services:
 ishare_ui:
    image: isharefoundation/ishare-satellite-ui:v3.0.2
    container_name: ishare_ui
    ports:
    - 4200:80
    environment:
      - API_URL=https://<UIHostName>/api
      - AUTH_REDIRECT_URI=https://<UIHostName>
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=https://<KeycloakHostName>/auth/
      - REALM_NAME=<ORG_NAME>
    restart: always
    networks:
    - net
